substitutions:
  name: "mypanel-woonkamer-sdl2"
  friendly_name: "Guition480-basic"


packages:
#  wifi: !include { file: modules//wifi/wifi.yaml, vars: {id: display_woonkamer }}


  # for simulation turn on device_sdl and turn off device_base
  device_base: !include packages/display_base.yaml
  #device_sdl: !include packages/display_sdl.yaml
  common_code: !include 
    file: packages/common_code.yaml  
    vars:
      name: "${name}"
      friendly_name: "${friendly_name}" 
      knop: "${knop}"
  start_page: !include 
    file: packages/startscherm.yaml
    vars:
      knop: "${knop}" 
  room_page: !include 
    file: packages/studeerkamer.yaml
    vars:
      knop: "${knop}" 
  woon_page: !include 
    file: packages/woonkamer.yaml
    vars:
      knop: "${knop}" 
  keuken_page: !include 
    file: packages/keuken.yaml
    vars:
      knop: "${knop}" 

  kluskamer__page: !include
    file: packages/kluskamer.yaml
    vars:
      knop: "${knop}" 

  weather_page: !include
    file: packages/weather.yaml
    vars:
      knop: "${knop}" 

  energy_page: !include
    file: packages/energy.yaml
    vars:
      knop: "${knop}" 


    


api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus    

lvgl:
  top_layer:
    widgets:
    - obj:
        styles: header_footer
        text_font: roboto20
        height: 30
        bg_color: 0x1c1c1c
        border_color: 0x1c1c1c 
        border_width: 0
        text_color: tft_white
        radius: 0
        scrollbar_mode: "OFF"
        align: top_left  
        widgets:  
          - label:
              align: top_right
              x: -2
              y: -10
              text: "\U000F05A9"
              id: lbl_hastatus
              hidden: true
          - label: 
              align: top_left
              y: -10
              id: title_time
              text: "00:00"
          - label: 
              align_to:
                id: title_time
                align: out_right_mid
              y: -5
              id: stookwijzer_label
              text: " \U000F0238"

          - label:
              align_to:
                id: stookwijzer_label
                align: out_right_mid
              y: -10
              id: afval_label2
              text: " Morgen: "
          
          - label:
              align_to:
                id: afval_label2
                align: out_right_mid
              y: -10
              id: afval_label
          
              
    - ${knop}matrix:
        align: bottom_mid
        styles: header_footer
        radius: 0
        #id: top_layer
        rows:
           - buttons:
              - id: page_home
                text: "\U000F02DC"
                on_press:
                  then:
                    lvgl.page.show: start_page
              - id: page_woonkamer
                text: "\U000F04B9"
                on_press:
                  then:
                    lvgl.page.show: woonkamer_page
              - id: page_keuken
                text: "\U000F04DE"
                on_press:
                  then:
                    lvgl.page.show: keuken_page
              - id: page_studeerkamer
                text: "\U000F095F"
                on_press:
                  then:
                    lvgl.page.show: studeer_page
              - id: page_kluskamer
                text: "${hammerscrewdriver}"
                on_press:
                  then:
                    lvgl.page.show: kluskamer_page

time:
  - platform: homeassistant
    id: time_comp
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: '0'
        then:
          - script.execute: time_update

script:
# Time update  
  - id: time_update
    then:
      - lvgl.label.update:
          id: title_time
          text: !lambda |-
            static char time_buf[17];
            auto now = id(time_comp).now();
            snprintf(time_buf, sizeof(time_buf), "%2d:%02d ", now.hour, now.minute );
            return time_buf;      

text_sensor:    
  - platform: homeassistant
    id: sensor_stookwijzer
    entity_id: sensor.stookwijzer
    on_value:
      - if:
          condition:
            lambda: |-
              return (0 == x.compare(std::string{"code_yellow"})) ;
          then:
            - lvgl.label.update:
                id: stookwijzer_label
                text: " \U000F0238"
                text_color: tft_yellow
          else:
            - lvgl.label.update:
                id: stookwijzer_label
                text: " \U000F0238"
                text_color: 0xFF3000 # red



# sensor.afvalinfo_huize_dartheide_trash_type_tomorrow
  - platform: homeassistant
    id: sensor_afval
    entity_id: sensor.afvalinfo_huize_dartheide_trash_type_tomorrow
    on_value:
      - if:
          condition:
            lambda: |-
              return (0 == x.compare(std::string{"geen"})) ;
          then:
            - lvgl.widget.hide: afval_label
            - lvgl.widget.hide: afval_label2
            
          else:
            - lvgl.label.update:
                id: afval_label
                text: !lambda 'return x.c_str();'


