captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${id} Fallback
    password: !secret wifi_password

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    id: wifi2
    update_interval: 60s

  - platform: template
    name: ${id} - Wifi signal
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi2).state < -92.0)
          return 100.0;
        if (id(wifi2).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi2).state * id(wifi2).state ) - ( 0.3794 * id(wifi2).state ) + 98.182 );

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
