
# LVGL configuration
lvgl:
  pages:
    - id: start_page
      styles: bg_white
      widgets:
        - obj: # Weer
            x: 10
            y: 40
            width: 225
            height: 150
            styles: bg_white

            widgets:
              - label:
                  text_font: weather_icons
                  id: home_weather_icon_now
                  text: "\U000F0599"
              # - label:
              #     text_font: roboto20
              #     align: bottom_left
              #     y: -30
              #     id: label_temperature_now
              #     text: "-"
              - label:
                  text_font: roboto20
                  align: bottom_left
                  y: -5
                  id: label_uv_index_now
                  text: "-"
              - label:
                  text_font: roboto20
                  align: bottom_right
                  id: forecast_temperature_current_high
                  text: '"'
                  y: -30
              - label:
                  text_font: roboto20
                  align: bottom_right
                  id: forecast_temperature_current_low
                  text: '"'
                  y: -5
              - label:
                  text_font: roboto20
                  id: text_weather_condition_now
                  text: ""
                  align: top_right

            on_press:
                then:
                  lvgl.page.show: weather_page
 
        - obj: # Energiescherm
            x: 245
            y: 40
            width: 225
            height: 150
            styles: bg_white
            scrollbar_mode: "OFF"
            widgets:
              - meter:
                  height: 120
                  width: 205
                  border_width: 0
                  bg_opa: TRANSP
                  align: CENTER
                  scales:
                    - range_from: -2000
                      range_to: 2000
                      angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: val_needle
                            width: 8
                            r_mod: 12 # sets line length by this much difference from the scale default radius
                            value: 0
                        - arc: # first half of the scale background
                            color: 0x00FF00 # green
                            r_mod: 10 # radius difference from the scale default radius
                            width: 31
                            start_value: -2000
                            end_value: 0
                        - arc: # second half of the scale background
                            color: 0xFF3000 # red
                            r_mod: 10
                            width: 31
                            start_value: 0
                            end_value: 2000

              - obj: # to cover the middle part of meter indicator line
                  radius: 70
                  styles: bg_white
                  pad_all: 0
                  align: CENTER
                  y: 40
                  on_press:
                    then:
                      lvgl.page.show: energy_page

              - label: # gauge numeric indicator
                  id: val_text
                  text_font: roboto20
                  align: bottom_mid
                  y: -20
                  text: 0
                  on_press:
                    then:
                      lvgl.page.show: energy_page

              - label: # 
                  text_font: roboto14
                  align: bottom_mid
                  y: 10
                  text: Grid
                  on_press:
                    then:
                      lvgl.page.show: energy_page
            on_press:
                then:
                  lvgl.page.show: energy_page

        - obj: # Treinlijst
            x: 10
            y: 200
            width: 460
            height: 160
            styles: bg_white
            scrollbar_mode: "OFF"
            widgets:
              - label:
                  text_font: weather_icons
                  text: "\U000F052C" # train 
                  align: left_mid            
              - label:
                  text_font: roboto16
                  id: text_ns_1
                  text: "-"
                  align: top_left
                  x: 75
              - label:
                  text_font: roboto16
                  id: text_ns_2
                  text: "-"
                  align: top_left
                  x: 75
                  y: 25
              - label:
                  text_font: roboto16
                  id: text_ns_3
                  text: "-"
                  align: top_left
                  x: 75
                  y: 50
              - label:
                  text_font: roboto16
                  id: text_ns_4
                  text: "-"
                  align: top_left
                  x: 75
                  y: 75
              - label:
                  text_font: roboto16
                  id: text_ns_5
                  text: "-"
                  align: top_left
                  x: 75
                  y: 100
            on_press:
              then:
                lvgl.page.show: ns_page



        - obj: # Status
            x: 10
            y: 370
            width: 460
            height: 50
            styles: bg_white
            scrollbar_mode: "OFF"
            widgets:
              - ${knop}:
                    id: start_lamp1
                    align: left_mid 
                    width: 150
                    height: 30
                    widgets:
                      - label:
                          text_font: roboto16
                          id: start_lamp1_label
                          text: "\U000F0336 Alle lichten uit"
                          align: left_mid
                    on_press:
                      then:
                        - homeassistant.action:
                            action: script.alle_lichten_uit

binary_sensor:
  - platform: status
    name: Status sensor

sensor:
  - platform: homeassistant
    id: sensor_sum_power_total
    entity_id: sensor.sum_power_total
    internal: true
    on_value:
      - lvgl.indicator.update:
          id: val_needle
          value: !lambda return x;
      - lvgl.label.update:
          id: val_text
          text:
            format: "%.0f W"
            args: [ 'x' ]


