packages:
  mediaplayer_studeerkamer: !include { file: ../modules/sonos/mediaplayersensors.yaml, vars: {id: studeerkamer }}
  cover1: !include { file: ../modules/cover/co_sensor.yaml, vars: {id: studeerkamer, entity_id: cover.gordijnen_studeer }}
  temp1: !include { file: ../modules/temp/temp_sensor.yaml, vars: {id: studeerkamer, entity_id: climate.bosch_radiatorkraan_studeerkamer_thermostat }}


# LVGL configuration
lvgl:
  pages:
    - id: studeer_page
      styles: bg_white
      widgets:
        - obj: !include { file: ../modules/sonos/mediaplayer.yaml, vars: {id: studeerkamer }}
                                               
        - obj: # Lampen
            x: 10
            y: 220
            width: 460
            height: 90
            styles: bg_white
            widgets:

              - ${knop}:  # Nieuw: Bureau-knop met dynamische tekst
                  id: desk_toggle
                  align: top_right
                  width: 135
                  height: 50
                  widgets:
                    - label:
                        id: desk_label
                        text: "\U000F1239 Bureau..."
                        align: left_mid
                  on_press:
                    - homeassistant.service:
                          service: cover.set_cover_position
                          data:
                            position: !lambda |-
                              return (id(desk_position).state == 23) ? 82 : 23;
                            entity_id: cover.desk_4728

        - obj: !include { file: ../modules/cover/gui_cover.yaml, vars: {id: studeerkamer, entity_id: cover.gordijnen_studeer, title: "Rolgordijnen", x_pos: "10" }}

        - obj: !include { file: ../modules/temp/gui_temp.yaml, vars: {id: studeerkamer, entity_id: climate.bosch_radiatorkraan_studeerkamer_thermostat }}

sensor:
  - platform: homeassistant
    entity_id: cover.desk_4728
    attribute: current_position
    id: desk_position
    on_value:
      - lambda: |-
          if (id(desk_position).state <= 23) {
              lv_label_set_text(id(desk_label), ("\U000F1239 Omhoog"));
          } else if (id(desk_position).state >= 82) {
              lv_label_set_text(id(desk_label), ("\U000F1239 Omlaag"));
          } else {
              lv_label_set_text(id(desk_label), ("\U000F1239 Bezig..."));
          }


