substitutions:
  pagina: "woonkamer"

packages:
  mediaplayer_woonkamer: !include { file: ../modules/sonos/mediaplayersensors.yaml, vars: {id: woonkamer }}
  lamp1: !include { file: ../modules/lamp/groeplamp_sensor.yaml, vars: {id: kamer, entity_id: light.woonkamer }}
  lamp2: !include { file: ../modules/lamp/groeplamp_sensor.yaml, vars: {id: erker, entity_id: light.erker }}
  lamp3: !include { file: ../modules/lamp/groeplamp_sensor.yaml, vars: {id: plafond, entity_id: light.plafondlamp_woonkamer }}
  cover1: !include { file: ../modules/cover/co_sensor.yaml, vars: {id: erker, entity_id: cover.gordijnen_erker }}

# LVGL configuration
lvgl:
  pages:
    - id: ${pagina}_page
      styles: bg_white
      widgets:
        - obj: !include { file: ../modules/sonos/mediaplayer.yaml, vars: {id: woonkamer }}
                                          
        - obj: # Lampen
            x: 10
            y: 220
            width: 460
            height: 90
            styles: bg_white
            widgets:
              - button: !include { file: ../modules/knop/licht.yaml, vars: {id: kamer, entity_id: light.woonkamer, pos: top_left }}                                    
              - button: !include { file: ../modules/knop/licht.yaml, vars: {id: erker, entity_id: light.erker, pos: top_mid }}
              - button: !include { file: ../modules/knop/licht.yaml, vars: {id: plafond, entity_id: light.plafondlamp_woonkamer, pos: top_right }}
              
        - obj: !include { file: ../modules/cover/gui_cover.yaml, vars: {id: erker, entity_id: cover.gordijnen_erker, title: "Gordijnen Erker" }}

        - obj: !include { file: ../modules/temp/gui_temp.yaml, vars: {id: woonkamer, entity_id: climate.bosch_radiatorkraan_woonkamer_thermostat }}
