substitutions:
  pagina: "woonkamer"

# LVGL configuration
lvgl:
  pages:
    - id: ${pagina}_page
      styles: bg_white
      widgets:
        - obj: # Media Player
            x: 10
            y: 40
            width: 460
            height: 170
            styles: bg_white

            widgets:
            - label:
                text: "${pagina}"
                align: top_right
                styles: bg_white
            - ${knop}: # Mute
                height: 40
                width: 50
                align: bottom_right
                widgets:
                    - label:
                        id: sonos_${pagina}_mute_button
                        text_font: mdi24
                        text: "${volume_icon}"
                        align: center
                on_click:
                  - homeassistant.service:
                      service: media_player.volume_mute
                      data:
                        entity_id: media_player.${pagina}
                        is_volume_muted: !lambda 'return !id(sonos_${pagina}_mute).state;'

            - ${knop}: # play/pause
                height: 40
                width: 50
                id: sonos_${pagina}_play_pause_button
                align_to:
                    id: sonos_${pagina}_mute_button
                    align: out_left_mid
                    x: -20
                widgets:
                  - label:
                      text_font: mdi24
                      text: "${play_pause_icon}"
                      align: center
                on_click:
                  - homeassistant.action:
                      action: media_player.media_play_pause
                      data_template:
                        entity_id: media_player.${pagina}
            - ${knop}: # stubru
                height: 40
                width: 50
                align_to:
                    id: sonos_${pagina}_play_pause_button
                    align: out_left_mid
                    x: -15
                id: sonos_${pagina}_stubru_button
                widgets:
                  - label:
                      text_font: roboto20
                      text: "stu\nbru"
                      align: center
                on_press:
                  then:
                    - homeassistant.action:
                        action: media_player.play_media
                        data_template:
                          entity_id: media_player.${pagina}   
                          media_content_type: "music"
                          media_content_id: "x-rincon-mp3radio://http://icecast.vrtcdn.be/stubru.aac"

            - ${knop}: # pinguin
                height: 40
                width: 50
                align_to:
                    id: sonos_${pagina}_stubru_button
                    align: out_left_mid
                    x: -15
                id: sonos_${pagina}_pinguin_button
                widgets:
                  - label:
                      text_font: mdi24
                      text: "\U000F0EC0"
                      align: center
                on_click:
                  - homeassistant.service:
                      service: media_player.play_media
                      data_template:
                        entity_id: media_player.${pagina}   
                        media_content_type: "music"
                        media_content_id: "http://streams.pinguinradio.com/PinguinClassics192.mp3"

            - ${knop}: # volume up
                height: 40
                width: 50
                align: bottom_left    
                x: 5
                id: sonos_${pagina}_volume_down
                widgets:
                  - label:
                      text_font: mdi24
                      text: "\U000F075E"
                      align: center
                on_click:
                  - homeassistant.service:
                      service: media_player.volume_down
                      data_template:
                        entity_id: media_player.${pagina}   
            
            - ${knop}: # volume down
                height: 40
                width: 50
                align: bottom_left    
                x: 65
                id: sonos_${pagina}_volume_up
                widgets:
                  - label:
                      text_font: mdi24
                      text: "\U000F075D"
                      align: center
                on_click:
                  - homeassistant.service:
                      service: media_player.volume_up
                      data_template:
                        entity_id: media_player.${pagina}   

            - label: # Artist
                id: display_sonos_${pagina}_media_artist
                text: "Artiest"
                align: left_mid
                y: -30
            - label: # Title
                id: display_sonos_${pagina}_title
                text: "Titel"
                align: left_mid
                y: -5
                                          
        - obj: # Lampen
            x: 10
            y: 220
            width: 460
            height: 90
            styles: bg_white
            widgets:
              - ${knop}:
                  align: top_left
                  width: 135
                  height: 50
                  widgets:
                    - label:
                        text_font: roboto20
                        id: ${pagina}_lamp1_label
                        text: "\U000F0336"
                        align: left_mid
                  on_press:
                    then:
                      - homeassistant.action:
                          action: script.woonkamer_toggle_licht
                                    
              - ${knop}:
                  id: ${pagina}_lamp2
                  align: top_mid
                  width: 135
                  height: 50
                  widgets:
                    - label:
                        text_font: roboto20
                        id: ${pagina}_lamp2_label
                        text: "\U000F0336"
                        align: left_mid
                  on_press:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: light.erker
              - ${knop}:
                  id: ${pagina}_${pagina}_lamp3
                  align: top_right
                  width: 135
                  height: 50
                  widgets:
                    - label:
                        text_font: roboto20
                        id: ${pagina}_lamp3_label
                        text: "\U000F0336"
                        align: left_mid
                  on_press:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: light.plafondlamp_woonkamer
              
        - obj: # Control card
            x: 10
            y: 320
            width: 225
            height: 100
            styles: bg_white
            widgets:
              - label:
                  text_font: roboto16
                  align: top_mid
                  y: -5
                  text: "Gordijnen Erker"
              - ${knop}:
                  width: 50
                  height: 40
                  align: bottom_left
                  widgets:
                  - label:
                      id: cov_up_${pagina}
                      text_font: mdi24
                      align: CENTER
                      text: "\U000F0143"
                  on_press:
                    - homeassistant.action:
                        action: cover.open_cover
                        data:
                          entity_id: cover.gordijnen_erker
              - ${knop}:
                  width: 65
                  height: 40
                  align: bottom_mid
                  widgets:
                  - label:
                      id: cov_stop_${pagina}
                      align: CENTER
                      text: STP
                  on_press:
                    - homeassistant.action:
                        action: cover.stop_cover
                        data:
                          entity_id: cover.gordijnen_erker
              - ${knop}:
                  width: 50
                  height: 40
                  align: bottom_right
                  widgets:
                  - label:
                      id: cov_down_${pagina} 
                      text_font: mdi24
                      align: CENTER
                      text: "\U000F0140"
                  on_press:
                    - homeassistant.action:
                        action: cover.close_cover
                        data:
                          entity_id: cover.gordijnen_erker

        - obj: # Temperatuur
                x: 245
                y: 320
                width: 225
                height: 100
                styles: bg_white
                widgets:
                    - ${knop}:
                        width: 50
                        height: 40
                        align: bottom_left
                        id: ${pagina}_spin_down
                        on_click:
                            - lvgl.spinbox.decrement: spinbox_${pagina}
                        widgets:
                            - label:
                                text: "-"
                                align: center
                    - spinbox:
                        styles: bg_white
                        id: spinbox_${pagina}
                        align: bottom_mid 
                        text_align: CENTER
                        width: 50
                        range_from: 21
                        range_to: 35
                        step: 0.5
                        rollover: false
                        digits: 3
                        decimal_places: 1
                        value: 22
                        on_value:
                            then:
                                - homeassistant.action:
                                    action: climate.set_temperature
                                    data:
                                        temperature: !lambda return x;
                                        entity_id: climate.bosch_radiatorkraan_${pagina}_thermostat
                    - ${knop}:
                        width: 50
                        height: 40
                        align: bottom_right
                        id: ${pagina}_spin_up
                        on_click:
                            - lvgl.spinbox.increment: spinbox_${pagina}
                        widgets:
                            - label:
                                text: "+"
                                align: center
                    - label:
                        text_font: roboto16
                        align: top_mid
                        text: "Temperatuur"
                  

sensor:
  - platform: homeassistant
    id: ${pagina}_thermostat
    entity_id: climate.bosch_radiatorkraan_${pagina}_thermostat
    attribute: temperature
    on_value:
      - lvgl.spinbox.update:
          id: spinbox_${pagina}
          value: !lambda return x;

  - platform: homeassistant
    id: media_player_volume_woonkamer
    entity_id: media_player.woonkamer

  - platform: homeassistant
    id: cover_${pagina}_pos
    entity_id: cover.gordijnen_erker
    attribute: current_position
    on_value:
      - if:
          condition:
            lambda: |-
              return x == 100;
          then:
            - lvgl.widget.update:
                id: cov_up_${pagina}
                text_opa: 60%
          else:
            - lvgl.widget.update:
                id: cov_up_${pagina}
                text_opa: 100%
      - if:
          condition:
            lambda: |-
              return x == 0;
          then:
            - lvgl.widget.update:
                id: cov_down_${pagina}
                text_opa: 60%
          else:
            - lvgl.widget.update:
                id: cov_down_${pagina}
                text_opa: 100%

binary_sensor:
  - platform: homeassistant
    id: sonos_${pagina}_mute
    entity_id: media_player.${pagina}
    attribute: is_volume_muted
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              lambda: 'return id(sonos_${pagina}_mute).state == true;'  # Controleer of de media player gemute is
            then:
              - lvgl.label.update:
                  id: sonos_${pagina}_mute_button
                  text: "${mute_icon}"
            else:
              - lvgl.label.update:
                  id: sonos_${pagina}_mute_button
                  text: "${volume_icon}"

text_sensor:
  # Gordijnen
  - platform: homeassistant
    id: cover_${pagina}_gordijnen
    entity_id: cover.gordijnen_erker
    on_value:
      - if:
          condition:
            lambda: |-
              return ((0 == x.compare(std::string{"opening"})) or (0 == x.compare(std::string{"closing"})));
          then:
            - lvgl.label.update:
                id: cov_stop_${pagina}
                text: "STOP"
          else:
            - lvgl.label.update:
                id: cov_stop_${pagina}
                text:
                  format: "%.0f%%"
                  args: [ 'id(cover_${pagina}_pos).get_state()' ]

  # Groep lampen woonkamer lamp1
  - platform: homeassistant
    id: remote_light1_${pagina}
    entity_id: light.woonkamer
    on_value:
      - if:
          condition:
            lambda: |-
              return (0 == x.compare(std::string{"on"})) ;
          then:
            - lvgl.label.update:
                id: ${pagina}_lamp1_label
                text: "\U000F1254 Kamer"
                text_color: tft_yellow
          else:
            - lvgl.label.update:
                id: ${pagina}_lamp1_label
                text: "\U000F1254 Kamer"
                text_color: tft_white

  # groep lampen erker lamp2
  - platform: homeassistant
    id: remote_light2_${pagina}
    entity_id: light.erker
    on_value:
      - if:
          condition:
            lambda: |-
              return (0 == x.compare(std::string{"on"})) ;
          then:
            - lvgl.label.update:
                id: ${pagina}_lamp2_label
                text: "\U000F1254 Erker"
                text_color: tft_yellow
          else:
            - lvgl.label.update:
                id: ${pagina}_lamp2_label
                text: "\U000F1254 Erker"
                text_color: tft_white

  # groep lampen plafond lamp3
  - platform: homeassistant
    id: remote_light3_${pagina}
    entity_id: light.plafondlamp_woonkamer
    on_value:
      - if:
          condition:
            lambda: |-
              return (0 == x.compare(std::string{"on"})) ;
          then:
            - lvgl.label.update:
                id: ${pagina}_lamp3_label
                text: "\U000F1254 Plafond"
                text_color: tft_yellow
          else:
            - lvgl.label.update:
                id: ${pagina}_lamp3_label
                text: "\U000F1254 Plafond"
                text_color: tft_white
          
  - platform: homeassistant
    id: sonos_${pagina}_media_title_text_sensor
    entity_id: media_player.${pagina}
    attribute: media_title
    on_value:
      then:
        - lvgl.label.update:
            id: display_sonos_${pagina}_title
            text: !lambda |-
              return id(sonos_${pagina}_media_title_text_sensor).state.c_str();

  - platform: homeassistant
    id: sonos_${pagina}_media_artist_text_sensor
    entity_id: media_player.${pagina}
    attribute: media_artist
    on_value:
      then:
        - lvgl.label.update:
            id: display_sonos_${pagina}_media_artist
            text: !lambda |-
              return id(sonos_${pagina}_media_artist_text_sensor).state.c_str();
